services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    volumes:
      - ./auth:/app
      - /app/node_modules
    ports:
      - "8500:8500"
    depends_on:
      - backend

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dev
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    ports:
      - "8501:8501"
    depends_on:
      - backend

  notfound:
    build:
      context: ./notfound
      dockerfile: Dockerfile.dev
    volumes:
      - ./notfound:/app
      - /app/node_modules
    ports:
      - "8502:8502"
    depends_on:
      - backend

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile.dev
    volumes:
      - ./orchestrator:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - backend
      - dashboard
      - auth
      - notfound
